# suppress inspection "UnusedProperty" for whole file
#The URL used for registering the device
registerUrl=https://risk-staging-api.inauth.com/v2/mobile/message
#The URL that log data is sent to
logUrl=https://risk-staging-api.inauth.com/v2/mobile/message
#The unique identifier for the customer account
accountGuid=42d296ad-1194-412c-b816-b4ed1a97add9
#The name of the server keys json file
serverKeysMessage=server_keys_message_hosted.json
#The interval time in days when sig lists will be updated
automaticUpdateInterval=14
#The application ID (optional)
#applicationId=myApplicationId